version: "3"

services:
  db:
    image: postgres:12.3
    hostname: db
    env_file:
      - .env

  redis:
    image: library/redis:5.0-alpine

  nginx:
    build:
      context: ./docker/nginx
    image: ${DOCKER_REPOSITORY}/nginx:${DOCKER_NGINX_VERSION}
    command: /run_nginx.sh
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: ${DOCKER_REPOSITORY}/app:${DOCKER_APP_VERSION}
    hostname: app
    env_file:
      - .env
    depends_on:
      - db
      - redis
