version: "3"

services:
  db:
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    volumes:
      - /var/lib/redis/data:/data

  nginx:
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - app-media:/app/media
      - app-static:/app/static

  app:
    restart: unless-stopped
    volumes:
      - app-media:/app/media
      - app-static:/app/static

  celery-worker:
    restart: unless-stopped
    volumes:
      - app-media:/app/media
      - app-static:/app/static

  celery-beat:
    restart: unless-stopped
    volumes:
      - app-media:/app/media
      - app-static:/app/static

volumes:
  app-media:
  app-static:
