version: "3"

services:
  db:
    environment:
      - POSTGRES_USER=eduon
      - POSTGRES_DB=eduon
      - POSTGRES_PASSWORD=eduon
    volumes:
      - eduon_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    ports:
      - 6379:6379
    volumes:
      - eduon_redis:/data

  nginx:
    volumes:
      - ./docker/nginx/letsencrypt/fullchain.pem:/etc/letsencrypt/live/${PRODUCTION_HOST}/fullchain.pem
      - ./docker/nginx/letsencrypt/privkey.pem:/etc/letsencrypt/live/${PRODUCTION_HOST}/privkey.pem
      - ./media:/app/media:ro
      - ./static:/app/static:ro
      - ./media_cdn:/app/media_cdn:ro
      - ./static_cdn:/app/static_cdn:ro

  app:
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
      - ./media_cdn:/app/media_cdn
      - ./static_cdn:/app/static_cdn
    command: python ./manage.py runserver 0.0.0.0:8000

  stream:
    volumes:
      - ./streaming:/app
      - ./streaming/media:/app/media
      - ./streaming/static:/app/static
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --workers ${UVICORN_WORKERS} --log-level 'info' --limit-max-requests 1000

  celery-worker:
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
      - ./media_cdn:/app/media_cdn
      - ./static_cdn:/app/static_cdn

  celery-beat:
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
      - ./media_cdn:/app/media_cdn
      - ./static_cdn:/app/static_cdn

volumes:
  eduon_db:
  eduon_redis:
