# Generated by Django 3.2.13 on 2022-06-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_speaker',
            field=models.BooleanField(default=False),
        ),
    ]
