# Generated by Django 3.2.13 on 2022-06-02 05:55

import accounts.models.account
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.account.upload_location),
        ),
    ]
