# Generated by Django 3.2.13 on 2022-06-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220424_0525'),
        ('accounts', '0005_devicemodel_otp'),
    ]

    operations = [
    ]
