# Generated by Django 3.2.13 on 2022-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0003_auto_20220424_0525_0005_devicemodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=21323433, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
