# Generated by Django 3.2.13 on 2022-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220623_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
