# Generated by Django 3.2.13 on 2022-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220623_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='enc_otp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
