# Generated by Django 3.2.13 on 2022-05-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='courses.categoriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255, verbose_name='tarriff')),
                ('lang', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('key_words', models.CharField(max_length=255)),
                ('what_to_learn', models.TextField()),
                ('whom_this_course', models.TextField()),
                ('students', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('certificates', models.CharField(max_length=255)),
                ('short_descr', models.TextField()),
                ('recommendation', models.TextField()),
                ('exchange_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.categoriesmodel')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.subcategoriesmodel')),
            ],
        ),
    ]
