# Generated by Django 3.2.13 on 2022-05-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_commentsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsmodel',
            options={'ordering': ('-date_created',)},
        ),
    ]
