# Generated by Django 3.2.13 on 2022-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_commentsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='discount_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
