# Generated by Django 3.2.13 on 2022-06-04 12:58

import courses.models.partners
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursemodel_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=courses.models.partners.upload_location)),
            ],
        ),
    ]
