# Generated by Django 3.2.13 on 2022-06-09 10:08

import courses.models.courses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_partnersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.courses.upload_location),
        ),
    ]
