# Generated by Django 3.2.13 on 2022-06-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursemodel_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='image',
        ),
    ]
