# Generated by Django 3.2.13 on 2022-06-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_coursemodel_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='students',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='trailer_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='courses.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LessonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_lesson_url', models.URLField(max_length=255, null=True)),
                ('subtitle_url', models.URLField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('module', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.modulemodel')),
            ],
        ),
    ]
