# Generated by Django 3.2.13 on 2022-06-30 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_auto_20220629_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='lessonsmodel',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lessonsmodel',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='lessonsmodel',
            name='resource_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='EnrolledCoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='courses.coursemodel')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
