# Generated by Django 3.2.13 on 2022-06-30 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_alter_ratingcoursesmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcoursesmodel',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ratingcoursesmodel',
            unique_together={('course', 'user')},
        ),
    ]
