# Generated by Django 3.2.13 on 2022-07-05 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_auto_20220630_1106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favcoursesmodel',
            unique_together={('course', 'user')},
        ),
    ]
