# Generated by Django 3.2.13 on 2022-07-13 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0017_alter_favcoursesmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledcoursesmodel',
            unique_together={('course', 'user')},
        ),
    ]
