# Generated by Django 3.2.13 on 2022-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_enrolledcoursesmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='is_valid',
            field=models.CharField(choices=[('on_hold', 'ON HOLD'), ('not valid', False), ('valid', True)], max_length=25, null=True),
        ),
    ]
