# Generated by Django 3.2.13 on 2022-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_coursemodel_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='is_valid',
            field=models.CharField(choices=[('on_hold', 'ON HOLD'), (False, 'NOT VALID'), (True, 'VALID')], max_length=25, null=True),
        ),
    ]
