# Generated by Django 3.2.13 on 2022-07-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_commentsmodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='is_valid',
            field=models.CharField(choices=[('ON HOLD', 'ON HOLD'), ('NOT VALID', 'NOT VALID'), ('VALID', 'VALID')], default='ON HOLD', max_length=25, null=True),
        ),
    ]
