# Generated by Django 3.2.13 on 2022-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_coursemodel_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsmodel',
            name='resolution_1080p',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonsmodel',
            name='resolution_240p',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonsmodel',
            name='resolution_360p',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonsmodel',
            name='resolution_480p',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonsmodel',
            name='resolution_720p',
            field=models.URLField(blank=True, null=True),
        ),
    ]
