# Generated by Django 3.2.13 on 2022-07-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20220726_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsmodel',
            name='duration',
        ),
    ]
