# Generated by Django 3.2.13 on 2022-07-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20220726_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsmodel',
            name='duration',
            field=models.DurationField(default=0, null=True),
        ),
    ]
