# Generated by Django 3.2.13 on 2022-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_lessonsmodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsmodel',
            name='lesson_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
