# Generated by Django 3.2.13 on 2022-07-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_lessonsmodel_lesson_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonsmodel',
            old_name='lesson_duration',
            new_name='duration',
        ),
    ]
