# Generated by Django 3.2.13 on 2022-06-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_walletmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletmodel',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='walletmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='walletmodel',
            name='wallet_name',
        ),
    ]
