# Generated by Django 3.2.13 on 2022-06-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20220607_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.walletmodel')),
            ],
        ),
    ]
