# Generated by Django 3.2.13 on 2022-06-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_voucherdefaultvaluemodel_vouchermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherDefaultValueModel',
        ),
        migrations.AddField(
            model_name='vouchermodel',
            name='value',
            field=models.BigIntegerField(default=50000),
        ),
    ]
