# Generated by Django 3.2.13 on 2022-06-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20220619_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
