# Generated by Django 3.2.13 on 2022-07-09 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0009_alter_transfermodel_date_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardmodel',
            unique_together={('owner', 'card_number')},
        ),
    ]
