# Generated by Django 3.2.13 on 2022-07-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_cardmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermodel',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
