# Generated by Django 3.2.13 on 2022-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20220718_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermodel',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
