# Generated by Django 3.2.13 on 2022-07-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_transfermodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfermodel',
            old_name='sender',
            new_name='destination',
        ),
    ]
