# Generated by Django 3.2.13 on 2022-07-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_rename_sender_transfermodel_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfermodel',
            options={'ordering': ('-date_created',)},
        ),
    ]
