# Generated by Django 3.2.13 on 2022-05-29 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursemodel_discount_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_justcartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='ordered',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemodel'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='JustCartModel',
        ),
    ]
