# Generated by Django 3.2.13 on 2022-06-09 06:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_partnersmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20220529_1733'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartmodel',
            unique_together={('owner', 'course')},
        ),
    ]
