# Generated by Django 3.2.13 on 2022-06-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='is_referral',
            field=models.BooleanField(default=False),
        ),
    ]
