# Generated by Django 3.2.13 on 2022-07-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_enrolledcoursesmodel_unique_together'),
        ('orders', '0005_cartmodel_is_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel'),
        ),
    ]
