# Generated by Django 3.2.13 on 2022-07-16 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0018_alter_enrolledcoursesmodel_unique_together'),
        ('orders', '0006_alter_cartmodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
